### ISSUE TITLE
Feature Request: Make generateRequest() return a Promise.

### ISSUE THREAD

**Issue by meneman** [wasc-io/iron-graphql#1]
At the moment generateRequest() sets lastResponse when the Promise is fullfilled. Besides calling this async function on the promise, you could also return it. So one can still listen for lastResponse, or if needed write a more complex then() function himself. In short, let generateRequest return the Promise at the end.

**Comment by NicolaiSchmid** [comment]
What exactly are you asking for?
Should the method `generateRequest` return the Promise of the Request itself, or should it return the response data (In my opinion better, because why should the user of the element be in charge of parsing the data?).

**Comment by NicolaiSchmid** [comment]
I actually needed the feature myself, so I just created a quick commit.
Are you satisfied with the new version?
